# First we will define the name of the process which is 'CI' which stands for Continuous Integration



# Now we define the Github Event which will trigger the CI build 



# We can define a single or multiple jobs which can be executed 



  # The name of the job is 'build'
  # Build is a common name for the job that is used to build the project
  # The ${{ }} are used as a means to reference configuration values from the matrix. 
  # Every possible permutation of Python versions 3.10 and 3.11 with the latest versions of Ubuntu, Mac OS and Windows operating systems will be tested.
  # we can expect 6 build jobs in total.


# A job is just a sequence of steps that are executed one by one 
    

    # We first checkout the code from the repository which copies the code from the local repository to the runner machine
    # The 'name' is just an optional label which is shown in the log - which helps in clarifying the process, which can be anything you want


# The next step is to install the dependencies required for the project.

    
# One of the most important steps in the CI process is to run the tests.
# In this case, we are using the PyTest framework to run the tests
